select t00.DIENSTBETREKKING, t10.OMSCHRIJVING, count(*)
from afas.AFAS_MDW_FORMATIE t00
 left join afas.AFAS_DIENSTBETREKKING t10
  on t00.DIENSTBETREKKING = t10.TABELWAARDE_CODE
group by t00.DIENSTBETREKKING, t10.OMSCHRIJVING
order by 1


select t00.DIENSTBETREKKING, t10.OMSCHRIJVING, count(*)
from afas.DIM_DIENSTVERBANDEN t00
 left join afas.AFAS_DIENSTBETREKKING t10
  on t00.DIENSTBETREKKING = t10.TABELWAARDE_CODE
group by t00.DIENSTBETREKKING, t10.OMSCHRIJVING
order by 1

select *
from afas.AFAS_DIENSTBETREKKING

select distinct REDEN_UIT_DIENST_CODE
from afas.AFAS_DIENSTPERIODES

select *
from afas.AFAS_MDW_FORMATIE t00


truncate table afas.DIM_DIENSTVERBANDEN

select * from afas.DIM_DIENSTVERBANDEN

-- 481.567

-- 963.134

select *
from afas.AFAS_DIENSTBETREKKING


select *
from afas.DIM_DIENSTVERBANDEN


update t00
set t00.DIENSTBETREKKING_OMS = t10.OMSCHRIJVING
from afas.DIM_DIENSTVERBANDEN t00
 join afas.AFAS_DIENSTBETREKKING t10
  on t00.DIENSTBETREKKING = t10.TABELWAARDE_CODE





